### ISSUE TITLE
Is pronto-haml being updated?

### ISSUE THREAD

**Issue by GregMacdonald** [prontolabs/pronto-haml#10]
The limitation on RuboCop < 1.0 just added and the lack of any real commits in a long time suggest this isn't being maintained. Is it significant work to update this for current RuboCop?

**Comment by doomspork** [comment]
@GregMacdonald these projects are still maintained but they all rely on the larger Pronto package which isn't as quick to iterate dependencies due to the work involved in breaking changes.

> Is it significant work to update this for current RuboCop?

Pull down the code, changing the dependency versions, and running to run the test suite is going to be your best indicator of LOE involved. We'd welcome a PR that helps bring dependencies up-to-date when possible :tada:

**Comment by GregMacdonald** [comment]
@doomspork I've no experience developing gems, so as soon as I can get to figuring out how to set up tests for this gem I'll give it a shot.

**Comment by ashkulz** [comment]
This should be addressed by #11, thanks to @nashby :tada:
